<?php
    // function to generate array of variables for WPML
	function theme_local_init() {
		global $is_inafx_local_init, $inafx_locals_arr;
		if ($is_inafx_local_init) return true;

		$inafx_locals_arr = array(
            // General
            'post' => __('Post', INAFX_THEME_DOMAIN),
            'posts' => __('Posts', INAFX_THEME_DOMAIN),
            'comment' => __('Comment', INAFX_THEME_DOMAIN),
            'comments' => __('Comments', INAFX_THEME_DOMAIN),
            'page' => __('Page', INAFX_THEME_DOMAIN),
            'pages' => __('Pages', INAFX_THEME_DOMAIN),
            'next' => __('Next', INAFX_THEME_DOMAIN),
            'previous' => __('Prev', INAFX_THEME_DOMAIN),

            //  /author-bio.php
			'author_view_all_posts' => __('view all posts', INAFX_THEME_DOMAIN),
            'social_follow' => __('Follow', INAFX_THEME_DOMAIN),
            'social_on' => __('on', INAFX_THEME_DOMAIN),
            'subscribe_rss_feed' => __('Subscribe RSS Feed', INAFX_THEME_DOMAIN),

            //  /comments.php
            'no_comments' => __('No comments yet.', INAFX_THEME_DOMAIN),
            'closed_comments' => __('Comments are closed.', INAFX_THEME_DOMAIN),

            //  /functions.php
            'home' => __('Home', INAFX_THEME_DOMAIN),
            'tag' => __('Tag', INAFX_THEME_DOMAIN),
            'archive' => __('Archive', INAFX_THEME_DOMAIN),
            'author' => __('Author', INAFX_THEME_DOMAIN),
            'blog_archives' => __('Blog Archives', INAFX_THEME_DOMAIN),
            'search_results_for' => __('Search Results for <em>"%1$s"</em>', INAFX_THEME_DOMAIN),
            'page_not_found' => __('Page Not Found', INAFX_THEME_DOMAIN),

            //  /admin/author/author-social.php
            'author_social_info' => __('Social Info', INAFX_THEME_DOMAIN),
            //  /admin/author/author-social.php
            //  /includes/widgets/my-social-widget.php
            'facebook_url' => __('Facebook URL', INAFX_THEME_DOMAIN),
            'twitter_url' => __('Twitter URL', INAFX_THEME_DOMAIN),
            'google_plus_url' => __('Google+ URL', INAFX_THEME_DOMAIN),
            'pinterest_url' => __('Pinterest URL', INAFX_THEME_DOMAIN),
            'linkedin_url' => __('Linkedin URL', INAFX_THEME_DOMAIN),
            'youtube_url' => __('Youtube URL', INAFX_THEME_DOMAIN),
            'vimeo_url' => __('Google+ URL', INAFX_THEME_DOMAIN),
            'skype_url' => __('Skype URL', INAFX_THEME_DOMAIN),
            'instagram_url' => __('Instagram URL', INAFX_THEME_DOMAIN),
            'flickr_url' => __('Flickr URL', INAFX_THEME_DOMAIN),
            'dribbble_url' => __('Dribbble URL', INAFX_THEME_DOMAIN),
            'behance_url' => __('Behance URL', INAFX_THEME_DOMAIN),
            'deviantart_url' => __('DeviantART URL', INAFX_THEME_DOMAIN),
            'github_url' => __('Github URL', INAFX_THEME_DOMAIN),
            'stumbleupon_url' => __('StumbleUpon URL', INAFX_THEME_DOMAIN),
            'reddit_url' => __('Reddit URL', INAFX_THEME_DOMAIN),
            'delicious_url' => __('Delicious URL', INAFX_THEME_DOMAIN),
            'soundcloud_url' => __('SoundCloud URL', INAFX_THEME_DOMAIN),
            'spotify_url' => __('Spotify URL', INAFX_THEME_DOMAIN),
            'rss_feed_url' => __('RSS Feed URL', INAFX_THEME_DOMAIN),

            //  /includes/post-formats/notfound.php
            'sorry' => __('Sorry!', INAFX_THEME_DOMAIN),
            'record_not_found' => __('No Posts/Pages Found.', INAFX_THEME_DOMAIN),

            //  /includes/post-formats/post-edit.php
            'edit' => __('Edit', INAFX_THEME_DOMAIN),

            //  /includes/likes.php
            'like_this' => __('Like this', INAFX_THEME_DOMAIN),
            'already_like_this' => __('You already like this', INAFX_THEME_DOMAIN),

            //  /includes/contact.php
            'contact_email_required' => __('Please enter your e-mail id.', INAFX_THEME_DOMAIN),
            'contact_email_invalid' => __('Please enter a valid e-mail.', INAFX_THEME_DOMAIN),
            'contact_name_required' => __('Please enter your name.', INAFX_THEME_DOMAIN),
            'contact_message_required' => __('Please enter your message.', INAFX_THEME_DOMAIN),

            //  /includes/sidebar-init.php
            'content_sidebar_name' => __('Content Widget Area', INAFX_THEME_DOMAIN),
            'content_sidebar_description' => __('Main sidebar that appears on the right.', INAFX_THEME_DOMAIN),
            'page_sidebar_name' => __('Page Widget Area', INAFX_THEME_DOMAIN),
            'page_sidebar_description' => __('Page sidebar that appears on the right.', INAFX_THEME_DOMAIN),
            'footer_sidebar_name' => __('Footer Widget Area', INAFX_THEME_DOMAIN),
            'footer_sidebar_description' => __('Footer sidebar that appears in the footer area.', INAFX_THEME_DOMAIN),

            //  /includes/theme-functions.php
            'thumbnail' => __('Thumbnail', INAFX_THEME_DOMAIN),
            'none' => __('none', INAFX_THEME_DOMAIN),
            'enter_name' => __('Enter Name...', INAFX_THEME_DOMAIN),
            'enter_email' => __('Enter Email...', INAFX_THEME_DOMAIN),
            'enter_comment' => __('Comment Here...', INAFX_THEME_DOMAIN),
            'comments_form_submit' => __('Post Comment', INAFX_THEME_DOMAIN),
            'comments_form_title' => __('Leave a Comment', INAFX_THEME_DOMAIN),
            'comments_form_notes' => __('All fields are required. Your email address will not be published.', INAFX_THEME_DOMAIN),
            'comment_moderation_awaited' => __('Your comment is awaiting moderation.', INAFX_THEME_DOMAIN),
            'reply' => __('Reply', INAFX_THEME_DOMAIN),
            'reply_login_text' => __('Log in to Reply', INAFX_THEME_DOMAIN),
            'comment_must_login' => __('You must be <a href="%1$s">logged in</a> to post a comment.', INAFX_THEME_DOMAIN),
            'comment_logged_in_as' => __('Logged in as <a href="%1$s">%2$s</a>. <a href="%3$s" title="Log out of this account">Log out?</a>', INAFX_THEME_DOMAIN),

            //  /includes/theme-postmeta.php
            'metabox_quote_settings' => __('Quote Settings', INAFX_THEME_DOMAIN),
            'metabox_quote_text' => __('Quote', INAFX_THEME_DOMAIN),
            'metabox_quote_text_desc' => __('Put quote in this field.', INAFX_THEME_DOMAIN),
            'metabox_quote_author' => __('Author', INAFX_THEME_DOMAIN),
            'metabox_quote_author_desc' => __('Put quote author in this field.', INAFX_THEME_DOMAIN),
            'metabox_link_settings' => __('Link Settings', INAFX_THEME_DOMAIN),
            'metabox_link_url' => __('The URL', INAFX_THEME_DOMAIN),
            'metabox_link_url_desc' => __('Insert the URL you wish to link to.', INAFX_THEME_DOMAIN),
            'metabox_link_text' => __('Link Text', INAFX_THEME_DOMAIN),
            'metabox_link_text_desc' => __('Text for the link.', INAFX_THEME_DOMAIN),
            'metabox_gallery_settings' => __('Gallery Settings', INAFX_THEME_DOMAIN),
            'metabox_gallery_type' => __('Gallery Type', INAFX_THEME_DOMAIN),
            'metabox_gallery_type_desc' => __('Choose gallery type.', INAFX_THEME_DOMAIN),
            'metabox_gallery_type_0' => __('== select slideshow type ==', INAFX_THEME_DOMAIN),
            'metabox_gallery_type_1' => __('slideshow', INAFX_THEME_DOMAIN),
            'metabox_gallery_type_2' => __('grid', INAFX_THEME_DOMAIN),
            'metabox_gallery_grid_height' => __('Height', INAFX_THEME_DOMAIN),
            'metabox_gallery_grid_height_desc' => __('The ideal height you want your row to be. It will not be exactly height that you have entered because plugin adjusts the row height to get the correct width. Play with this value because it will affect on image tile displaying. This only works with grid type gallery format.', INAFX_THEME_DOMAIN),
            'metabox_gallery_grid_margins' => __('Margins', INAFX_THEME_DOMAIN),
            'metabox_gallery_grid_margins_desc' => __('Decide the margins between the images.', INAFX_THEME_DOMAIN),
            'metabox_audio_settings' => __('Audio Settings', INAFX_THEME_DOMAIN),
            'metabox_audio_embed' => __('Embed Code', INAFX_THEME_DOMAIN),
            'metabox_audio_embed_desc' => __('You can include embedded code from soundcloud.com here.<br><b>Attention!</b> This code will overwrite your audio URL(s).', INAFX_THEME_DOMAIN),
            'metabox_video_settings' => __('Video Settings', INAFX_THEME_DOMAIN),
            'metabox_video_embed' => __('Embed Video Code', INAFX_THEME_DOMAIN),
            'metabox_video_embed_desc' => __('Enter the url to the video file.<br><br>YouTube Video<br>Enter the full url to the video page like this:<br><code>http://youtube.com/watch?v=aBcdeFghIjK</code><br><br>Vimeo Video<br>Enter the full url to the video page like this:<br><code>http://vimeo.com/1234567</code>', INAFX_THEME_DOMAIN),

            //  /includes/unattach.php
            'unattach_link_text' => __('Unattach', INAFX_THEME_DOMAIN),
            'unattach_link_title' => __('Unattach this media item.', INAFX_THEME_DOMAIN),

            //  /loop/loop-archives.php
            'archives_recent_posts' => __('Recent Posts', INAFX_THEME_DOMAIN),
            'archives_by_month' => __('Archives by Month', INAFX_THEME_DOMAIN),
            'archives_by_year' => __('Archives by Year', INAFX_THEME_DOMAIN),
            'archives_by_category' => __('Archives by Category', INAFX_THEME_DOMAIN),
            'archives_by_tag' => __('Archives by Tag', INAFX_THEME_DOMAIN),
            'archives_by_author' => __('Archives by Author', INAFX_THEME_DOMAIN),

            //  /static/static-404.php
            'go_to_home' => __('Go to Homepage', INAFX_THEME_DOMAIN),

            //  /static/static-search.php
            'search_field_placeholder' => __('SEARCH HERE...', INAFX_THEME_DOMAIN),

            //  /includes/widgets/display-widgets.php
            'dw_show_widget_for' => __('Show Widget for:', INAFX_THEME_DOMAIN),
            'dw_everyone' => __('Everyone', INAFX_THEME_DOMAIN),
            'dw_loggedout_users' => __('Logged-out users', INAFX_THEME_DOMAIN),
            'dw_loggedin_users' => __('Logged-in users', INAFX_THEME_DOMAIN),
            'dw_hide_on_checked' => __('Hide on checked pages', INAFX_THEME_DOMAIN),
            'dw_show_on_checked' => __('Show on checked pages', INAFX_THEME_DOMAIN),
            'dw_toggle_misc' => __('Miscellaneous', INAFX_THEME_DOMAIN),
            'dw_toggle_pages' => __('Pages', INAFX_THEME_DOMAIN),
            'dw_toggle_custom_post_types' => __('Custom Post Types', INAFX_THEME_DOMAIN),
            'dw_toggle_custom_post_archives' => __('Custom Post Type Archives', INAFX_THEME_DOMAIN),
            'dw_toggle_categories' => __('Categories', INAFX_THEME_DOMAIN),
            'dw_toggle_taxonomies' => __('Taxonomies', INAFX_THEME_DOMAIN),
            'dw_toggle_languages' => __('Languages', INAFX_THEME_DOMAIN),
            'dw_post_ids_list' => __('Comma Separated list of IDs of posts not listed above', INAFX_THEME_DOMAIN),
            'dw_page' => __('Page', INAFX_THEME_DOMAIN),
            'dw_archive' => __('Archive', INAFX_THEME_DOMAIN),
            'dw_page_type_front' => __('Front', INAFX_THEME_DOMAIN),
            'dw_page_type_blog' => __('Blog', INAFX_THEME_DOMAIN),
            'dw_page_type_archives' => __('Archives', INAFX_THEME_DOMAIN),
            'dw_page_type_single_post' => __('Single Post', INAFX_THEME_DOMAIN),
            'dw_page_type_404' => __('404', INAFX_THEME_DOMAIN),
            'dw_page_type_search' => __('Search', INAFX_THEME_DOMAIN),

            //  /includes/widgets/my-ad125-widget.php
            'widget_ad125_title' => __('INAFX - 125x125 Ads', INAFX_THEME_DOMAIN),
            'widget_ad125_desc' => __('Add 125x125 ads.', INAFX_THEME_DOMAIN),
            'widget_ad125_label' => __('Title', INAFX_THEME_DOMAIN),
            'widget_ad125_imgurl_label' => __('Image URL', INAFX_THEME_DOMAIN),
            'widget_ad125_adlink_label' => __('Ad Link', INAFX_THEME_DOMAIN),
            'widget_ad125_ad1_label' => __('Ad 1', INAFX_THEME_DOMAIN),
            'widget_ad125_ad2_label' => __('Ad 2', INAFX_THEME_DOMAIN),
            'widget_ad125_ad3_label' => __('Ad 3', INAFX_THEME_DOMAIN),
            'widget_ad125_ad4_label' => __('Ad 4', INAFX_THEME_DOMAIN),

            //  /includes/widgets/my-ad300-widget.php
            'widget_ad300_title' => __('INAFX - 300px (width) Ad', INAFX_THEME_DOMAIN),
            'widget_ad300_desc' => __('Add 300px (width) ad.', INAFX_THEME_DOMAIN),
            'widget_ad300_label' => __('Title', INAFX_THEME_DOMAIN),
            'widget_ad300_ad_label' => __('Ad 300px (width)', INAFX_THEME_DOMAIN),
            'widget_ad300_imgurl_label' => __('Image URL', INAFX_THEME_DOMAIN),
            'widget_ad300_adlink_label' => __('Ad Link', INAFX_THEME_DOMAIN),

            //  /includes/widgets/my-ad-widget.php
            'widget_adbanner_title' => __('INAFX - Ad Banner', INAFX_THEME_DOMAIN),
            'widget_adbanner_desc' => __('Add ad banner.', INAFX_THEME_DOMAIN),
            'widget_adbanner_label' => __('Title', INAFX_THEME_DOMAIN),
            'widget_adbanner_ad_label' => __('Ad Banner', INAFX_THEME_DOMAIN),
            'widget_adbanner_imgurl_label' => __('Image URL', INAFX_THEME_DOMAIN),
            'widget_adbanner_adlink_label' => __('Ad Link', INAFX_THEME_DOMAIN),

            //  /includes/widgets/my-flickr-widget.php
            'widget_flickr_title' => __('INAFX - Flickr', INAFX_THEME_DOMAIN),
            'widget_flickr_desc' => __('A widget that displays the latest flickr images', INAFX_THEME_DOMAIN),
            'widget_flickr_label' => __('Title', INAFX_THEME_DOMAIN),
            'widget_flickr_id_label' => __('Flickr ID', INAFX_THEME_DOMAIN),
            'widget_flickr_count_label' => __('Images Count', INAFX_THEME_DOMAIN),
            'widget_flickr_linktext_label' => __('Link Text', INAFX_THEME_DOMAIN),

            //  /includes/widgets/my-instagram-widget.php
            'widget_instagram_title' => __('INAFX - Instagram', INAFX_THEME_DOMAIN),
            'widget_instagram_desc' => __('A widget that displays the latest Instagram images', INAFX_THEME_DOMAIN),
            'widget_instagram_label' => __('Title', INAFX_THEME_DOMAIN),
            'widget_instagram_id_label' => __('Instagram user ID', INAFX_THEME_DOMAIN),
            'widget_instagram_token_label' => __('Instagram access token', INAFX_THEME_DOMAIN),
            'widget_instagram_count_label' => __('Images Count', INAFX_THEME_DOMAIN),
            'widget_instagram_showlikes_label' => __('Show Likes', INAFX_THEME_DOMAIN),
            'widget_instagram_showcaption_label' => __('Show Caption', INAFX_THEME_DOMAIN),
            'widget_instagram_config_error' => __('Configuration error occurred or no pictures found...', INAFX_THEME_DOMAIN),

            //  /includes/widgets/my-social-widget.php
            'widget_social_title' => __('INAFX - Social Networks', INAFX_THEME_DOMAIN),
            'widget_social_desc' => __('Link to your social networks.', INAFX_THEME_DOMAIN),
            'widget_social_label' => __('Title', INAFX_THEME_DOMAIN),

            //  /includes/widgets/my-tabbed-widget.php
            'widget_tabbed_title' => __('INAFX - Tabbed Posts', INAFX_THEME_DOMAIN),
            'widget_tabbed_desc' => __('A widget that displays the tabbed recent/popular posts.', INAFX_THEME_DOMAIN),
            'widget_tabbed_posts_title' => __('Tabbed Posts', INAFX_THEME_DOMAIN),
            'widget_tabbed_recentposts_label' => __('Recent Posts Title', INAFX_THEME_DOMAIN),
            'widget_tabbed_popularposts_label' => __('Popular Posts Title', INAFX_THEME_DOMAIN),
            'widget_tabbed_postscount_label' => __('Posts Count', INAFX_THEME_DOMAIN),
            'widget_tabbed_recentposts_title' => __('Recent Posts', INAFX_THEME_DOMAIN),
            'widget_tabbed_popularposts_title' => __('Popular Posts', INAFX_THEME_DOMAIN),

            //  /includes/widgets/my-twitter-widget.php
            'widget_twitter_title' => __('INAFX - Twitter', INAFX_THEME_DOMAIN),
            'widget_twitter_desc' => __('A widget that displays the latest tweets.', INAFX_THEME_DOMAIN),
            'widget_twitter_default_title' => __('Latest Tweets', INAFX_THEME_DOMAIN),
            'widget_twitter_label' => __('Title', INAFX_THEME_DOMAIN),
            'widget_twitter_id_label' => __('Twitter Widget ID', INAFX_THEME_DOMAIN),
            'widget_twitter_count_label' => __('Number of Tweets', INAFX_THEME_DOMAIN),

            //  /admin/framework/options-init.php
            'opt_yes' => __('yes', INAFX_THEME_DOMAIN),
            'opt_no' => __('no', INAFX_THEME_DOMAIN),
            'opt_display_name' => __('INAfx', INAFX_THEME_DOMAIN),
            'opt_footer_credits' => __('Theme options <strong>(INAfx v1.0)</strong> provided by <strong>INA Brains</strong> and proudly powered by <strong>Redux Framework</strong>.', INAFX_THEME_DOMAIN),
            'opt_theme_options_menu_text' => __('Theme Options', INAFX_THEME_DOMAIN),
            'opt_theme_options_page_title' => __('Theme Options', INAFX_THEME_DOMAIN),
            // general section
            'opt_general' => __('General', INAFX_THEME_DOMAIN),
            'opt_general_desc' => __('General Settings for background color of page body, font family and color of body content and h1 - h6 headings.', INAFX_THEME_DOMAIN),
            'opt_body_bg' => __('Body Background', INAFX_THEME_DOMAIN),
            'opt_body_bg_desc' => __('Body background with image or color.', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern' => __('Body Background Pattern', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_desc' => __('Select any pattern for the page background.', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_hint_title' => __('<strong>Body Background Pattern</strong>', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_hint_desc' => __('Choose a page background pattern from the predefined set. <strong><em>It will override the backgroud color or image applied in the previous option. Select the first blank pattern to use the body background color or image option.</em></strong>', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_alt0' => __('pattern 0', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_alt1' => __('pattern 1', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_alt2' => __('pattern 2', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_alt3' => __('pattern 3', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_alt4' => __('pattern 4', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_alt5' => __('pattern 5', INAFX_THEME_DOMAIN),
            'opt_body_bgpattern_alt6' => __('pattern 6', INAFX_THEME_DOMAIN),
            'opt_body_font' => __('Body Font', INAFX_THEME_DOMAIN),
            'opt_body_font_desc' => __('Specify the body font properties.', INAFX_THEME_DOMAIN),
            'opt_h1_font' => __('H1 Heading Font', INAFX_THEME_DOMAIN),
            'opt_h1_font_desc' => __('Specify the h1 heading font properties.', INAFX_THEME_DOMAIN),
            'opt_h2_font' => __('H2 Heading Font', INAFX_THEME_DOMAIN),
            'opt_h2_font_desc' => __('Specify the h2 heading font properties.', INAFX_THEME_DOMAIN),
            'opt_h3_font' => __('H3 Heading Font', INAFX_THEME_DOMAIN),
            'opt_h3_font_desc' => __('Specify the h3 heading font properties.', INAFX_THEME_DOMAIN),
            'opt_h4_font' => __('H4 Heading Font', INAFX_THEME_DOMAIN),
            'opt_h4_font_desc' => __('Specify the h4 heading font properties.', INAFX_THEME_DOMAIN),
            'opt_h5_font' => __('H5 Heading Font', INAFX_THEME_DOMAIN),
            'opt_h5_font_desc' => __('Specify the h5 heading font properties.', INAFX_THEME_DOMAIN),
            'opt_h6_font' => __('H6 Heading Font', INAFX_THEME_DOMAIN),
            'opt_h6_font_desc' => __('Specify the h6 heading font properties.', INAFX_THEME_DOMAIN),
            'opt_display_search' => __('Display Search', INAFX_THEME_DOMAIN),
            'opt_display_search_desc' => __('Show/hide search in the header', INAFX_THEME_DOMAIN),
            'opt_display_tagline' => __('Header Tagline', INAFX_THEME_DOMAIN),
            'opt_display_tagline_desc' => __('Show/hide the tagline.', INAFX_THEME_DOMAIN),
            'opt_display_page_titles' => __('Display page titles.', INAFX_THEME_DOMAIN),
            'opt_display_page_titles_desc' => __('Show/hide page titles above breadcrumbs.', INAFX_THEME_DOMAIN),
            'opt_display_titles_home' => __('Display page titles on home.', INAFX_THEME_DOMAIN),
            'opt_display_titles_home_desc' => __('Show/hide page titles on home page.', INAFX_THEME_DOMAIN),
            'opt_display_breadcrumbs' => __('Display breadcrumbs', INAFX_THEME_DOMAIN),
            'opt_display_breadcrumbs_desc' => __('Show/hide breadcrumbs navigation on pages', INAFX_THEME_DOMAIN),
            'opt_enable_nicescroll' => __('Enable NiceScroll', INAFX_THEME_DOMAIN),
            'opt_enable_nicescroll_desc' => __('Enable/Disable NiceScroll for pages', INAFX_THEME_DOMAIN),
            'opt_google_api_key' => __('Google API Key', INAFX_THEME_DOMAIN),
            'opt_google_api_key_desc' => __('Specify the Google API key for Maps.', INAFX_THEME_DOMAIN),
            'opt_google_api_key_desc_2' => __('You can learn how to get <a href="https://developers.google.com/maps/documentation/javascript/tutorial#api_key" target="_blank">Google API key here.</a>', INAFX_THEME_DOMAIN),

            // header styles section
            'opt_header_styles' => __('Header styles', INAFX_THEME_DOMAIN),
            'opt_header_styles_desc' => __('Settings for background image of Header, overlay color and its alpha transparency, search icon color, sticky header effect, and showing Slideshow/Masonry Grid of Postings in the Header area.', INAFX_THEME_DOMAIN),
            'opt_header_bg' => __('Header Background', INAFX_THEME_DOMAIN),
            'opt_header_bg_desc' => __('Header background with image', INAFX_THEME_DOMAIN),
            'opt_header_overlay' => __('Header Overlay Color', INAFX_THEME_DOMAIN),
            'opt_header_overlay_desc' => __('Pick an overlay color for the header', INAFX_THEME_DOMAIN),
            'opt_header_transparency' => __('Header overlay transparency', INAFX_THEME_DOMAIN),
            'opt_header_transparency_desc' => __('Set an alpha transparency for the header overlay.', INAFX_THEME_DOMAIN),
            'opt_header_transparency_desc_2' => __('values between 0 and 1', INAFX_THEME_DOMAIN),
            'opt_header_fore_color' => __('Header Text Color', INAFX_THEME_DOMAIN),
            'opt_header_fore_color_desc' => __('Pick a color for text in header', INAFX_THEME_DOMAIN),
            'opt_header_type' => __('Select header type', INAFX_THEME_DOMAIN),
            'opt_header_type_desc' => __('Set the header type normal/sticky', INAFX_THEME_DOMAIN),
            'opt_header_normal' => __('Normal header', INAFX_THEME_DOMAIN),
            'opt_header_sticky' => __('Sticky header', INAFX_THEME_DOMAIN),
            'opt_header_ephemera' => __('Header Ephemera', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_desc' => __('Show/hide the postings cycle widget in the header area.', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_style' => __('Header Ephemera Style', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_style_desc' => __('Select grid/slideshow style for header postings cycle.', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_slideshow_1' => __('Slideshow 1', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_slideshow_2' => __('Slideshow 2', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_slide_interval' => __('Slideshow Time Interval', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_slide_interval_desc' => __('Number of milliseconds between slide transitions.', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_slide_interval_desc_2' => __('<strong>hint:</strong> 1000 milliseconds = 1 second', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_items' => __('Header Ephemera Items', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_items_desc' => __('Select the header postings to be retrieved from categories, tags or selected Post Ids', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_items_posts' => __('Posts', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_items_categories' => __('Categories', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_items_tags' => __('Tags', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_posts' => __('Select Postings', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_posts_desc' => __('Search and Select multiple posts.', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_posts_desc_2' => __('<strong>hint:</strong> Enter 3 or more characters to search the postings.', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_categories' => __('Select Categories', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_categories_desc' => __('Search and Select multiple categories.', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_posts_count' => __('Postings Count', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_posts_count_desc' => __('Number of postings to load', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_tags' => __('Select Tags', INAFX_THEME_DOMAIN),
            'opt_header_ephemera_tags_desc' => __('Search and Select multiple tags.', INAFX_THEME_DOMAIN),

            // theme styles section
            'opt_theme_styles' => __('Theme styles', INAFX_THEME_DOMAIN),
            'opt_theme_styles_desc' => __('Select the color scheme for the theme from 5 predefined colors or choose any custom color of your choice. It will instantly build a new skin for the theme.', INAFX_THEME_DOMAIN),
            'opt_theme_preset_type' => __('Theme Preset Type', INAFX_THEME_DOMAIN),
            'opt_theme_preset_type_desc' => __('Choose predefined color or custom color of your choice.', INAFX_THEME_DOMAIN),
            'opt_theme_preset_colors_type' => __('Preset Colors', INAFX_THEME_DOMAIN),
            'opt_theme_custom_colors_type' => __('Custom Color', INAFX_THEME_DOMAIN),
            'opt_theme_preset_colors' => __('Theme Presets', INAFX_THEME_DOMAIN),
            'opt_theme_preset_colors_desc' => __('Select any base theme color.', INAFX_THEME_DOMAIN),
            'opt_theme_base_color_1' => __('color 1', INAFX_THEME_DOMAIN),
            'opt_theme_base_color_2' => __('color 2', INAFX_THEME_DOMAIN),
            'opt_theme_base_color_3' => __('color 3', INAFX_THEME_DOMAIN),
            'opt_theme_base_color_4' => __('color 4', INAFX_THEME_DOMAIN),
            'opt_theme_base_color_5' => __('color 5', INAFX_THEME_DOMAIN),
            'opt_theme_custom_colors' => __('Custom Color', INAFX_THEME_DOMAIN),
            'opt_theme_custom_colors_desc' => __('Select your custom base theme color.', INAFX_THEME_DOMAIN),

            // logo & favicon section
            'opt_logo_favicon' => __('Logo & Favicon', INAFX_THEME_DOMAIN),
            'opt_logo_favicon_desc' => __('Settings for uploading logo, fav-icon and sticky header effects.', INAFX_THEME_DOMAIN),
            'opt_logo_type' => __('Logo Type', INAFX_THEME_DOMAIN),
            'opt_logo_type_desc' => __('What kind of logo you want to show?', INAFX_THEME_DOMAIN),
            'opt_logo_type_desc_2' => __('You can display either image type or text type logo', INAFX_THEME_DOMAIN),
            'opt_logo_type_image' => __('Image Logo', INAFX_THEME_DOMAIN),
            'opt_logo_type_text' => __('Text Logo', INAFX_THEME_DOMAIN),
            'opt_logo_image' => __('Image Logo type', INAFX_THEME_DOMAIN),
            'opt_logo_image_desc' => __('Upload a transparent .png image logo.', INAFX_THEME_DOMAIN),
            'opt_logo_image_desc_2' => __('Best fit logo size = <strong>200px x 52px</strong>', INAFX_THEME_DOMAIN),
            'opt_logo_text' => __('Logo Text', INAFX_THEME_DOMAIN),
            'opt_logo_text_desc' => __('Specify some text as site logo.', INAFX_THEME_DOMAIN),
            'opt_logo_text_default' => __('<span class="fa fa-terminal"></span> baseBlog', INAFX_THEME_DOMAIN),
            'opt_logo_typography_normal' => __('Logo typography [Normal]', INAFX_THEME_DOMAIN),
            'opt_logo_typography_normal_desc' => __('Logo text typography for normal header mode.', INAFX_THEME_DOMAIN),
            'opt_logo_typography_sticky' => __('Logo typography [Sticky]', INAFX_THEME_DOMAIN),
            'opt_logo_typography_sticky_desc' => __('Reduced logo text typography for sticky header mode.', INAFX_THEME_DOMAIN),
            'opt_favicon' => __('Favicon', INAFX_THEME_DOMAIN),
            'opt_favicon_desc' => __('Upload a favicon for your site.', INAFX_THEME_DOMAIN),

            // navigation section
            'opt_navigation' => __('Navigation', INAFX_THEME_DOMAIN),
            'opt_navigation_desc' => __('Setting the typography for Header navigation menu.', INAFX_THEME_DOMAIN),
            'opt_navigation_menu_typography' => __('Menu typography', INAFX_THEME_DOMAIN),
            'opt_navigation_menu_typography_desc' => __('Choose the font properties of your choice.', INAFX_THEME_DOMAIN),

            // blog section
            'opt_blog' => __('Blog', INAFX_THEME_DOMAIN),
            'opt_blog_desc' => __('Settings for Blog options such as pagination types, and meta information of postings.', INAFX_THEME_DOMAIN),
            'opt_blog_home_title' => __('Blog Home Page Title', INAFX_THEME_DOMAIN),
            'opt_blog_home_title_desc' => __('Specify a title for blog home page.', INAFX_THEME_DOMAIN),
            'opt_blog_home_title_default' => __('Blog', INAFX_THEME_DOMAIN),
            'opt_pagination_type' => __('Pagination Type', INAFX_THEME_DOMAIN),
            'opt_pagination_type_desc' => __('What kind of pagination you want to show?', INAFX_THEME_DOMAIN),
            'opt_pagination_type_desc_2' => __('You can display either page numbers or next/prev links', INAFX_THEME_DOMAIN),
            'opt_pagination_page_numbers' => __('Page Numbers', INAFX_THEME_DOMAIN),
            'opt_pagination_next_prev_links' => __('Next/Prev Links', INAFX_THEME_DOMAIN),
            'opt_show_related_posts' => __('Show Related Posts', INAFX_THEME_DOMAIN),
            'opt_show_related_posts_desc' => __('Show/hide related posts widget.', INAFX_THEME_DOMAIN),
            'opt_related_posts_title' => __('Related Posts title', INAFX_THEME_DOMAIN),
            'opt_related_posts_title_desc' => __('Specify a title for related posts.', INAFX_THEME_DOMAIN),
            'opt_related_posts_title_default' => __('Related Posts', INAFX_THEME_DOMAIN),
            'opt_related_posts_count' => __('Related Posts Count', INAFX_THEME_DOMAIN),
            'opt_related_posts_count_desc' => __('Specify the number of related posts to load.', INAFX_THEME_DOMAIN),
            'opt_show_full_posts' => __('Show Full Posts', INAFX_THEME_DOMAIN),
            'opt_show_full_posts_desc' => __('Show full posting on blog page.', INAFX_THEME_DOMAIN),
            'opt_show_readmore' => __('Show Readmore Button', INAFX_THEME_DOMAIN),
            'opt_show_readmore_desc' => __('Show read more button under the postings on blog page.', INAFX_THEME_DOMAIN),
            'opt_readmore_text' => __('Readmore button text', INAFX_THEME_DOMAIN),
            'opt_readmore_text_desc' => __('Specify the text for read more button.', INAFX_THEME_DOMAIN),
            'opt_readmore_text_default' => __('Continue Reading...', INAFX_THEME_DOMAIN),
            'opt_excerpt_words_limit' => __('Excerpt Words Limit', INAFX_THEME_DOMAIN),
            'opt_excerpt_words_limit_desc' => __('Specify the words limit for excerpts field.', INAFX_THEME_DOMAIN),
            'opt_show_author_bio' => __('Show Author\'s Bio Info', INAFX_THEME_DOMAIN),
            'opt_show_author_bio_desc' => __('Show/hide author\'s bio info under the posting and archive page.', INAFX_THEME_DOMAIN),
            'opt_show_post_meta' => __('Show Post meta info', INAFX_THEME_DOMAIN),
            'opt_show_post_meta_desc' => __('Show/hide all the meta info fields of postings.', INAFX_THEME_DOMAIN),
            'opt_show_post_type_icon' => __('Show Post Type Icon', INAFX_THEME_DOMAIN),
            'opt_show_post_type_icon_desc' => __('Show/hide post-format type icon.', INAFX_THEME_DOMAIN),
            'opt_show_post_author' => __('Show Post Author', INAFX_THEME_DOMAIN),
            'opt_show_post_author_desc' => __('Show/hide author name of postings.', INAFX_THEME_DOMAIN),
            'opt_post_author_prefix_text' => __('Post author prefix text', INAFX_THEME_DOMAIN),
            'opt_post_author_prefix_text_desc' => __('Sepcify a prefix text for author name.', INAFX_THEME_DOMAIN),
            'opt_post_author_prefix_text_default' => __('By', INAFX_THEME_DOMAIN),
            'opt_show_post_date_published' => __('Show Post Date Published', INAFX_THEME_DOMAIN),
            'opt_show_post_date_published_desc' => __('Show/hide published date of postings.', INAFX_THEME_DOMAIN),
            'opt_post_date_format' => __('Post Date Format', INAFX_THEME_DOMAIN),
            'opt_post_date_format_desc' => __('Specify a valid format for published date.', INAFX_THEME_DOMAIN),
            'opt_post_date_format_desc_2' => __('Here are all WordPress supported formats:<br /> <a href="http://codex.wordpress.org/Formatting_Date_and_Time" target="_blank">http://codex.wordpress.org/Formatting_Date_and_Time</a>', INAFX_THEME_DOMAIN),
            'opt_show_post_categories' => __('Show Post Category(s)', INAFX_THEME_DOMAIN),
            'opt_show_post_categories_desc' => __('Show/hide categories of postings.', INAFX_THEME_DOMAIN),
            'opt_show_post_tags' => __('Show Post Tags', INAFX_THEME_DOMAIN),
            'opt_show_post_tags_desc' => __('Show/hide tags of postings.', INAFX_THEME_DOMAIN),
            'opt_show_post_comments_count' => __('Show Number of Comments', INAFX_THEME_DOMAIN),
            'opt_show_post_comments_count_desc' => __('Show/hide comments count of postings.', INAFX_THEME_DOMAIN),

            // social networks section
            'opt_social_networks' => __('Social Networks', INAFX_THEME_DOMAIN),
            'opt_social_networks_desc' => __('Settings to show/hide social networks under the postings and author.', INAFX_THEME_DOMAIN),
            'opt_display_author_social_icons' => __('Display Author\'s Social Icons', INAFX_THEME_DOMAIN),
            'opt_display_author_social_icons_desc' => __('Show/Hide author\'s social icons in Author Biography description box.', INAFX_THEME_DOMAIN),
            'opt_display_post_social_icons' => __('Display Blog Posts Social Sharing', INAFX_THEME_DOMAIN),
            'opt_display_post_social_icons_desc' => __('Show/Hide social sharing icons under the blog postings.', INAFX_THEME_DOMAIN),
            'opt_display_facebook_icon' => __('Display facebook icon', INAFX_THEME_DOMAIN),
            'opt_display_facebook_icon_desc' => __('Show/hide facebook icon under the post.', INAFX_THEME_DOMAIN),
            'opt_display_twitter_icon' => __('Display twitter icon', INAFX_THEME_DOMAIN),
            'opt_display_twitter_icon_desc' => __('Show/hide twitter icon under the post.', INAFX_THEME_DOMAIN),
            'opt_display_google_plus_icon' => __('Display google-plus icon', INAFX_THEME_DOMAIN),
            'opt_display_google_plus_icon_desc' => __('Show/hide google-plus icon under the post.', INAFX_THEME_DOMAIN),
            'opt_display_digg_icon' => __('Display digg icon', INAFX_THEME_DOMAIN),
            'opt_display_digg_icon_desc' => __('Show/hide digg icon under the post.', INAFX_THEME_DOMAIN),
            'opt_display_reddit_icon' => __('Display reddit icon', INAFX_THEME_DOMAIN),
            'opt_display_reddit_icon_desc' => __('Show/hide reddit icon under the post.', INAFX_THEME_DOMAIN),
            'opt_display_linkedin_icon' => __('Display linkedin icon', INAFX_THEME_DOMAIN),
            'opt_display_linkedin_icon_desc' => __('Show/hide linkedin icon under the post.', INAFX_THEME_DOMAIN),
            'opt_display_pinterest_icon' => __('Display pinterest icon', INAFX_THEME_DOMAIN),
            'opt_display_pinterest_icon_desc' => __('Show/hide pinterest icon under the post.', INAFX_THEME_DOMAIN),
            'opt_display_stumbleupon_icon' => __('Display stumbleupon icon', INAFX_THEME_DOMAIN),
            'opt_display_stumbleupon_icon_desc' => __('Show/hide stumbleupon icon under the post.', INAFX_THEME_DOMAIN),
            'opt_display_delicious_icon' => __('Display delicious icon', INAFX_THEME_DOMAIN),
            'opt_display_delicious_icon_desc' => __('Show/hide delicious icon under the post.', INAFX_THEME_DOMAIN),
            'opt_display_mail_icon' => __('Display mail icon', INAFX_THEME_DOMAIN),
            'opt_display_mail_icon_desc' => __('Show/hide mail icon under the post.', INAFX_THEME_DOMAIN),


            // footer section
            'opt_footer' => __('Footer', INAFX_THEME_DOMAIN),
            'opt_footer_desc' => __('Settings for footer area to specify footer copyright text and google analytics code.', INAFX_THEME_DOMAIN),
            'opt_footer_copyright_text' => __('Footer copyright text', INAFX_THEME_DOMAIN),
            'opt_footer_copyright_text_desc' => __('Specify a text string for copyright text in the footer area.', INAFX_THEME_DOMAIN),
            'opt_footer_copyright_text_default' => __('Copyright 2014 <a href="#">baseBlog</a>. All Rights Reserved.', INAFX_THEME_DOMAIN),
            'opt_google_analytics' => __('Google Analytics code', INAFX_THEME_DOMAIN),
            'opt_google_analytics_desc' => __('Copy/Paste the goolge analytics code script taken from Google Analytics.', INAFX_THEME_DOMAIN),

            // contact form section
            'opt_contact_form' => __('Contact Form', INAFX_THEME_DOMAIN),
            'opt_contact_form_desc' => __('Settings for Contact form to specify the e-mail address for receiving contact mail and success/error message on form submission.', INAFX_THEME_DOMAIN),
            'opt_contact_mailto' => __('Mail To', INAFX_THEME_DOMAIN),
            'opt_contact_mailto_desc' => __('E-mail address where you want to receive the contact mail.', INAFX_THEME_DOMAIN),
            'opt_contact_subject_line' => __('Subject Line', INAFX_THEME_DOMAIN),
            'opt_contact_subject_line_desc' => __('Subject line for e-mail that you will receive from the site.', INAFX_THEME_DOMAIN),
            'opt_contact_subject_line_default' => __('New Contact Mail', INAFX_THEME_DOMAIN),
            'opt_contact_success_message' => __('Success Message', INAFX_THEME_DOMAIN),
            'opt_contact_success_message_desc' => __('Message to display when e-mail sending works successfully.', INAFX_THEME_DOMAIN),
            'opt_contact_success_message_default' => __('Mail sent successfully :)', INAFX_THEME_DOMAIN),
            'opt_contact_error_message' => __('Error Message', INAFX_THEME_DOMAIN),
            'opt_contact_error_message_desc' => __('Message to display when e-mail sending fails.', INAFX_THEME_DOMAIN),
            'opt_contact_error_message_default' => __('Mail was not sent :(', INAFX_THEME_DOMAIN),

            // 404 page section
            'opt_404_page' => __('404 Page', INAFX_THEME_DOMAIN),
            'opt_404_page_desc' => __('404 Page Settings to upload a background image, color overlay and text strings to be display on page.', INAFX_THEME_DOMAIN),
            'opt_404_page_bg' => __('Page Background', INAFX_THEME_DOMAIN),
            'opt_404_page_bg_desc' => __('Page background with image', INAFX_THEME_DOMAIN),
            'opt_404_bg_overlay' => __('Background Overlay Color', INAFX_THEME_DOMAIN),
            'opt_404_bg_overlay_desc' => __('Pick an overlay color for the page', INAFX_THEME_DOMAIN),
            'opt_404_bg_overlay_transparency' => __('Background Overlay Transparency', INAFX_THEME_DOMAIN),
            'opt_404_bg_overlay_transparency_desc' => __('Set an alpha transparency for the overlay.', INAFX_THEME_DOMAIN),
            'opt_404_bg_overlay_transparency_desc_2' => __('values between 0 and 1', INAFX_THEME_DOMAIN),
            'opt_404_title_line_1' => __('Title line 1', INAFX_THEME_DOMAIN),
            'opt_404_title_line_1_desc' => __('First text string for 404 page.', INAFX_THEME_DOMAIN),
            'opt_404_title_line_1_default' => __('Oops, This Page Could Not Be Found Here!', INAFX_THEME_DOMAIN),
            'opt_404_title_line_1_font' => __('Fonts - Title Line 1', INAFX_THEME_DOMAIN),
            'opt_404_title_line_1_font_desc' => __('Specify the font properties for title line 1.', INAFX_THEME_DOMAIN),
            'opt_404_title_line_2' => __('Title line 2', INAFX_THEME_DOMAIN),
            'opt_404_title_line_2_desc' => __('Second title string for 404 page.', INAFX_THEME_DOMAIN),
            'opt_404_title_line_2_default' => __('404', INAFX_THEME_DOMAIN),
            'opt_404_title_line_2_font' => __('Fonts - Title Line 2', INAFX_THEME_DOMAIN),
            'opt_404_title_line_2_font_desc' => __('Specify the font properties for title line 2.', INAFX_THEME_DOMAIN),

            // import/export section
            'opt_import_export' => __('Import / Export', INAFX_THEME_DOMAIN),
            'opt_import_export_desc' => __('Import and Export your framework settings from file, text or URL.', INAFX_THEME_DOMAIN),

			'' => '' // empty value
		);
		$is_inafx_local_init = true;
	};

	function theme_locals($label) {
		global $inafx_locals_arr;
		theme_local_init();
		return $inafx_locals_arr[$label];
	};
?>